Repository valist-io/valist-js, pull requests merged in 2022-12, with the labels that each got.

#299 Switch to self-hosted IPFS with CAR uploads
  package-lock.json
  packages/valist-sdk/package.json
  packages/valist-sdk/src/client.ts
  packages/valist-sdk/src/index.ts
Labels: bug

#318 Fix deploy success message
  packages/valist-web/pages/-/account/[account]/project/[project]/deployments.tsx
Labels: bug

#325 Add title to project & account profile
  packages/valist-web/pages/[account]/[project]/index.tsx
  packages/valist-web/pages/[account]/index.tsx
Labels: bug

#326 Change pinning provider to Infura
  package-lock.json
  packages/valist-cli/package.json
  packages/valist-cli/src/commands/download.ts
  packages/valist-cli/test/commands/download.test.ts
  packages/valist-cli/test/commands/publish.test.ts
  packages/valist-sdk/package.json
  packages/valist-sdk/src/client.ts
  packages/valist-sdk/src/index.ts
  packages/valist-sdk/tests/client.spec.ts
  packages/valist-ui/src/components/FileButton/FileButton.tsx
  packages/valist-web/forms/create-account.tsx
  packages/valist-web/forms/create-project.tsx
  packages/valist-web/forms/create-release.tsx
  packages/valist-web/forms/update-account.tsx
  packages/valist-web/forms/update-project.tsx
  packages/valist-web/forms/utils.tsx
Labels: enhancement

#331 Add issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs_report.yml
Labels: documentation, enhancement

#328 Valist SDK & CLI 2.7.1
  package-lock.json
  packages/valist-cli/README.md
  packages/valist-cli/package.json
  packages/valist-cli/src/commands/download.ts
  packages/valist-cli/src/commands/publish.ts
  packages/valist-cli/test/commands/publish.test.ts
  packages/valist-sdk/data/data/data2/test3.txt
  packages/valist-sdk/data/data/data2/test4.txt
  packages/valist-sdk/data/data/test1.txt
  packages/valist-sdk/data/data/test2.txt
  packages/valist-sdk/data/data3/test5.txt
  packages/valist-sdk/package.json
  packages/valist-sdk/src/client.ts
  packages/valist-sdk/src/index.ts
  packages/valist-sdk/src/metatx.ts
  packages/valist-sdk/tests/client.spec.ts
  packages/valist-ui/package.json
  packages/valist-ui/src/components/AsyncInput/AsyncInput.tsx
  packages/valist-ui/src/components/CircleButton/CircleButton.styles.ts
  packages/valist-ui/src/components/CircleButton/CircleButton.tsx
  packages/valist-ui/src/components/CircleButton/index.ts
  packages/valist-ui/src/components/Header/Header.styles.ts
  packages/valist-ui/src/components/Header/Header.tsx
  packages/valist-ui/src/components/ImageInput/ImageInput.tsx
  packages/valist-ui/src/components/Tag/Tag.styles.ts
  packages/valist-ui/src/components/Tag/Tag.tsx
  packages/valist-ui/src/components/Tag/index.ts
  packages/valist-ui/src/components/ThemeButton/ThemeButton.tsx
  packages/valist-ui/src/components/ThemeProvider/components/Tabs.ts
  packages/valist-ui/src/index.ts
  packages/valist-web/components/AccountProvider/AccountProvider.tsx
  packages/valist-web/components/AccountProvider/index.ts
  packages/valist-web/components/AccountSelect/AccountSelect.tsx
  packages/valist-web/components/AddressInput/AddressInput.tsx
  packages/valist-web/components/CreateAccount/CreateAccount.tsx
  packages/valist-web/components/CreateProject/CreateProject.tsx
  packages/valist-web/components/DiscoveryCard/DiscoveryCard.tsx
  packages/valist-web/components/Layout/Layout.tsx
  packages/valist-web/components/NameInput/NameInput.tsx
  packages/valist-web/forms/create-release.tsx
  packages/valist-web/forms/update-account.tsx
  packages/valist-web/forms/update-project.tsx
  packages/valist-web/package.json
  packages/valist-web/pages/-/account/[account]/project/[project]/create/release.tsx
  packages/valist-web/pages/-/account/[account]/project/[project]/settings.tsx
  packages/valist-web/pages/-/account/[account]/settings.tsx
  packages/valist-web/pages/-/activity.tsx
  packages/valist-web/pages/-/dashboard.tsx
  packages/valist-web/pages/-/members.tsx
  packages/valist-web/pages/_app.tsx
  packages/valist-web/pages/index.tsx
  packages/valist-web/utils/discover.ts
  packages/valist-web/utils/github.ts
Labels: bug, enhancement
