Repository valist-io/valist-js, pull requests merged in 2022-09, with the labels that each got.

#247 Add cache headers to next config
  packages/valist-web/next.config.js
Labels: enhancement

#259 Rename magic login option to email
  packages/valist-ui/src/components/Carousel/CarouselItem.tsx
  packages/valist-web/components/RainbowKitProvider/connectors.ts
  packages/valist-web/public/images/mail.svg
Labels: bug, enhancement

#263 Add download/launch stats
  packages/valist-ui/src/components/PublishPromo/PublishPromo.styles.ts
  packages/valist-web/pages/-/discover.tsx
  packages/valist-web/pages/[account]/[project]/index.tsx
  packages/valist-web/public/images/discovery/publish_today.png
Labels: enhancement

#264 Fix stats helper in sdk
  packages/valist-sdk/src/utils.ts
Labels: bug

#266 Filter by released on discovery page
  packages/valist-web/graphql/Discover.graphql
  packages/valist-web/pages/-/discover.tsx
Labels: enhancement
